### ISSUE TITLE
Error on missing token for unused services

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinaai-py#17]
I'm building a script *just* for testing SceneXplain, with this code snippet:

```python
from jinaai import JinaAI

jinaai = JinaAI(
    secrets = {
        'scenex-secret': 'xxx',
    }
)
```

Running that code throws the error:

```text
Traceback (most recent call last):
  File "/mnt/data/work/testing/scenex/test-all-algos.py", line 12, in <module>
    jinaai = JinaAI(
             ^^^^^^^
  File "/mnt/data/work/testing/scenex/env/lib/python3.11/site-packages/jinaai/__init__.py", line 9, in __init__
    PPSecret = f"token {secrets['promptperfect-secret']}" if secrets else ''
                        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'promptperfect-secret'
```

We shouldn't assume that every user has signed up for *all* AIGC apps

**Comment by alexcg1** [comment]
Do we have a rough timeline on this? @scott-martens plans to write a JinaChat post using the package, but this bug would complicate that

**Comment by redjson** [comment]
Already done https://github.com/jina-ai/jinaai-py/commit/454c7cd5686ce536f851f09dcd1dd7998e92b2dc but not published yet

**Comment by redjson** [comment]
I released the new version
