### ISSUE TITLE
Support chat streaming

### ISSUE THREAD

**Issue by ashiishme** [jina-ai/jinaai-py#18]
The API client for JinaChat currently responds only when the full chat is returned by the server. It seems the streaming is not yet implemented.

We are currently working on the JinaChat Plugin that uses `jinaai-py` package internally for [LLM CLI](https://github.com/simonw/llm) tool. The cli tool supports the streaming feature but currently cannot be used by JinaChat plugin until this package supports it.

I think same applies for the JavaScript package but not required at the moment.

**Comment by redjson** [comment]
Done & published. Here is how to use it: https://github.com/jina-ai/jinaai-py/blob/main/tests/real-cases/test_ex4-email.py
